on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

name: Create Release

jobs:
  release:
    name: Build release artifacts and create a release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build Packs
        run: npm run pullJSONtoLDB --if-present
      - name: Create zip archive
        run: git archive --format=zip --prefix=neon-lords/ -o neon-lords.zip ${{ github.ref }}
      - name: Add pack files to zip
        run: zip -ur neon-lords.zip packs -p neon-lords/
      - name: Create release draft
        uses: softprops/action-gh-release@v2
        with:
          files: |
            neon-lords.zip
            system.json
          overwrite: true
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}


