on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

name: Create Release

jobs:
  release:
    name: Build release artifacts and create a release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build Packs
        run: npm run pullJSONtoLDB --if-present
      - name: Create zip archive
        run: git archive --format=zip --prefix=neon-lords/ -o neon-lords.zip ${{ github.ref }}
      - name: Add pack files to zip
        run: zip -ur neon-lords.zip -n neon-lords packs
      - name: Create release draft
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          draft: true
          prerelease: false
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      - name: Upload system.json
        uses: actions/upload-release-asset@v1
        id: upload-release-asset-json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./system.json
          asset_name: system.json
          asset_content_type: application/json
      - name: Upload neon-lords.zip
        uses: actions/upload-release-asset@v1
        id: upload-release-asset-zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neon-lords.zip
          asset_name: neon-lords.zip
          asset_content_type: application/zip


